### ISSUE TITLE
Include in F-Droid?

### ISSUE THREAD

**Issue by TPS** [fython-tools/DocUIProxy-Android#2]
@fython Your [Night Screen](https://github.com/fython/Blackbulb) is already [on F-Droid](https://f-droid.org/en/packages/info.papdt.blackblub/).  [Would you be ok w/ this app, also?](https://gitlab.com/fdroid/rfp/issues/956)

@IzzySoft I'd appreciate your analysis, also, re: the [already-released APKs](https://github.com/fython-tools/DocUIProxy-Android/releases).

**Comment by IzzySoft** [comment]
@TPS I saw the APKs. But isn't WeChat the Chinese pendant to WA or FB-Chat? In that case it wouldn't fit into my repo anyway.

Let's wait for the bot's results first. The app isn't listed at Play, so there won't be any Exodus results… ah well, it's a bit manual work to do a manual scan, but here you go with what my scanner detected:

* Android Support v4 (Development Framework)
* Androidx Core (Utility)
* RxJava (Utility)
* Reactive Streams (Utility)

No show-stopper from this end.

**Comment by fython** [comment]
@IzzySoft I will continue to add more features and it won't be a tool for WeChat only. I need some time to prepare for releasing. Thanks for your attention and help.

**Comment by IzzySoft** [comment]
@fython thanks! I don't thing WeChat support is an issue for the official repo (it just causes the `NonFreeNet` AntiFeature). Just for mine I declared Facebook and the likes off-limit. So just follow the link from the initial post by @TPS :smiley:

**Comment by TPS** [comment]
@fython Are you @fython @ GitLab, also?  If not, I don't know whether you saw that the F-Droid 🤖 choked a little on how your version values are setup in the repo.…

**Comment by fython** [comment]
@TPS Sorry for replying so late. I fell into a downturn in these days and now I start to solve these problems. I have released a new version after fixing `insecure-gradlew` . BTW, my GitLab username is `@fython1` .

**Comment by fython** [comment]
I made version code and name inlined in `app/build.gradle` too. Then F-Droid bot may works fine now.

**Comment by IzzySoft** [comment]
Going by the last tag (1.2.1), unfortunately not: versionName and versionCode [in the gradle](https://github.com/fython-tools/DocUIProxy-Android/blob/1.2.1/app/build.gradle#L10) still use variables. So we must wait for a tag pointing to a later commit that has the "literals" before triggering the bot again. Of course you could "move" the current 1.2.1 tag, if there's nothing speaking against that from your end.

**Comment by fython** [comment]
@TPS @IzzySoft I have recreated a [`1.2.1` tag](https://github.com/fython-tools/DocUIProxy-Android/releases/tag/1.2.1) just now.

**Comment by IzzySoft** [comment]
Thanks! I've marked it for a rescan then. And to not have to search for the corresponding issue at F-Droid each time: [Here's the RFP](https://gitlab.com/fdroid/rfp/issues/956).

**Comment by TPS** [comment]
@fython We're concerned that this app is now abandoned.  True?

**Comment by fython** [comment]
@TPS Yes. It probably won't be maintained anymore.

**Comment by IzzySoft** [comment]
Sad to read – but thanks for the honest answer! Guess we should then close the RFP?

**Comment by TPS** [comment]
> @TPS Yes. It probably won't be maintained anymore.

@fython Maybe to make it extra clear, maybe archive the repo?
